### ISSUE TITLE
No fc2 prefix as per XML user guide on fincen for CTR/SAR

### ISSUE THREAD

**Issue by mimy2001** [moov-io/fincen#38]
FinCEN Version: `0.2.6`

**What were you trying to do?**
Generate a CTR / SAR report 

**What did you expect to see?**
elements should have a prefix of fc2 

![image](https://user-images.githubusercontent.com/16566431/200403738-a033bc7e-42d0-44ab-9d33-22c8c278236b.png)

**What did you see?**
Don't have fc2 

![image](https://user-images.githubusercontent.com/16566431/200403704-214fae9d-74a5-43d3-831e-ce0df84a26e7.png)

**How can we reproduce the problem?**

Here's the user guide where it mentions this: 
![image](https://user-images.githubusercontent.com/16566431/200403493-6cf13cc8-2b3c-40a8-92c8-be5a75e3e152.png)

**Comment by mimy2001** [comment]
@mfdeveloper508 here's the new issue I opend up for the namespace prefix

**Comment by mfdeveloper508** [comment]
Fixed and merged to mater branch 
please check with new version

**Comment by mimy2001** [comment]
I don't see a newer version than 0.2.6 -> how should I grab a new dependency? @mfdeveloper508

**Comment by mfdeveloper508** [comment]
Created new version (0.2.8)
