### ISSUE TITLE
Unable to check Yes to only initial report indicator and still include fincen direct backfile indicator or corrects amends prior report indicator in CTR generation

### ISSUE THREAD

**Issue by mimy2001** [moov-io/fincen#40]
FinCEN Version: `0.2.6`

**What were you trying to do?**

Generate the CTR report with Activity Association with just Y in initial report indicator but still include the other two elements as empty (CorrectsAmendsPriorReportIndicator and FinCENDirectBackFileIndicator) as show in the user guide 

**What did you expect to see?**
I expected to see the following, where I can check yes to 1 of the indicators and then provide empty to the rest

<img width="1418" alt="Screen Shot 2022-11-07 at 6 28 00 PM" src="https://user-images.githubusercontent.com/16566431/200437311-363282f1-bf22-4356-9e30-57e419094586.png">

<img width="1418" alt="Screen Shot 2022-11-07 at 6 29 36 PM" src="https://user-images.githubusercontent.com/16566431/200437352-c11b5eae-3505-4006-952c-7ab7d14f048e.png">

**What did you see?**
If i don't include the other two it's ok, but the userguide has them in but just no value (ie not Y but empty indicator)

**How can we reproduce the problem?**
Create a CTR report with this code : 

```
	aat := currency_transaction.ActivityAssociationType{
		SeqNum: fincen.SeqNumber(seqNumber),
		// CorrectsAmendsPriorReportIndicator: &EmptyIndicator, // TODO how to do this since it fails validation, must be recorded even if it's nil as per CTR XSD
		// FinCENDirectBackFileIndicator:      &EmptyIndicator,
		InitialReportIndicator: &YesIndicator,
	}

activity.ActivityAssociation = &aat

```

**Comment by mfdeveloper508** [comment]
https://github.com/moov-io/fincen/pull/43

I used 2 types for indicator, we need to use 
- ValidateIndicatorType (for required field)
- ValidateIndicatorNullType (for omitempty field)
