### ISSUE TITLE
How to setup fincen in python?

### ISSUE THREAD

**Issue by iamrraj** [moov-io/fincen#58]
FinCEN Version: ``

**What were you trying to do?**
I am trying to setup FinCEN on python to submit a case file. or how can i set up FinCEN on server to transfer XML case file.

**Comment by adamdecaf** [comment]
You can run the docker image or Go binary. Then make an HTTP request with python to `localhost:8206`

https://github.com/moov-io/fincen#docker

**Comment by adamdecaf** [comment]
Please comment or reopen this PR if you have more questions. We're on [slack in the `#fincen` room](https://slack.moov.io/) as well.

**Comment by iamrraj** [comment]
Hey, @adamdecaf  I managed to set it up through  Docker, so my question is there any way to submit a **SAR** file to the " BSA E-Filing" platform using FinCEN?  can you please guide me to do it?

**Comment by adamdecaf** [comment]
We don't currently support submitting SAR files, but would like to work on adding that. 

https://www.fincen.gov/resources/filing-information
https://bsaefiling.fincen.treas.gov/main.html
